// AUTO-GENERATED by src/build.ts (npm run build:schemas). Do not edit by hand.
// Authoring sections inlined from src/authoring.md so the MCP server runs without
// a filesystem (e.g. Cloudflare Workers).
import type { AuthoringSection } from './authoring.ts';
export const AUTHORING: AuthoringSection[] = [
  {
    "id": "overview",
    "title": "Overview: native vs presentation",
    "when": "first time authoring an entry.yaml; understand what to fill vs leave to native",
    "body": "`entry.yaml` is a **presentation overlay**. Native data (`plugin.json`,\n`commands/*.md`, `skills/*/SKILL.md`, `.mcp.json`, `hooks.json`) already yields a\nvalid manifest. Everything in `entry.yaml` is **optional enrichment** — write\nonly what native can't express, or where you want curated copy.\n\nRule: presentation never restates native facts. The generator joins the two by\nplugin id (= directory name). If a field has a native fallback (e.g. `tagline`\nfalls back to the plugin description), author it only when the curated wording\nbeats the native one.\n\nPoint your editor at the schema for completion:\n`# yaml-language-server: $schema=node_modules/@xbluesky/cc-marketspec/schemas/entry.schema.json`"
  },
  {
    "id": "tagline-intro",
    "title": "tagline & intro",
    "when": "writing the card summary and lede for a plugin",
    "body": "- `tagline` — one line for cards and meta. Falls back to the native plugin\n  description. Write one only if you can beat it: concrete, benefit-first, no\n  trailing period needed. ~60–80 chars reads best on a card.\n- `intro` — the full lede (a short paragraph). Falls back to native description.\n  Use YAML block scalar (`>`) for multi-line. Say what it does and who it's for;\n  don't repeat the tagline verbatim.\n\n```yaml\ntagline: Headless data standard + generator for a marketplace's presentation\nintro: >\n  Describe your marketplace as data; cc-marketspec joins it with native plugin\n  manifests, validates, and emits one render-agnostic manifest.json.\n```"
  },
  {
    "id": "tips-traps",
    "title": "tips & traps",
    "when": "adding power-moves (tips) or pitfalls/gotchas (traps) to a plugin",
    "body": "Both are arrays of short notes (≤ 280 chars each).\n\n- `tips` — **positive power-moves**: non-obvious ways to get more out of the\n  plugin. Imperative, specific.\n- `traps` — **negative gotchas / pitfalls**: what bites people. Name the\n  symptom and the fix.\n\nEach item is either a plain string (simplest) **or** an object when you need a\nlink:\n\n```yaml\ntips:\n  - Run /cc-check in CI to gate PRs before the manifest is regenerated.\n  - text: Self-host the MCP on Cloudflare Workers for zero-install schema help.\n    href: https://github.com/XBlueSky/cc-marketspec#hosted-mcp-server\n    label: Hosted MCP guide\ntraps:\n  - entry.yaml never restates native facts — a skill trigger that just repeats\n    the SKILL.md description adds nothing and clutters the card.\n```\n\nUse the object form only when a link genuinely helps; otherwise the string form\nkeeps the file readable. `label` (≤ 120 chars) is the link text."
  },
  {
    "id": "group-ccVersion",
    "title": "group & ccVersion",
    "when": "classifying a plugin into a catalog group or stating a min Claude Code version",
    "body": "- `group` — the id of a `catalog.yaml` group (you author the group taxonomy\n  there). Distinct from the native `category` in `marketplace.json`. Must match a\n  declared group or the build errors.\n- `ccVersion` — minimum Claude Code version. No native source, so author it if\n  the plugin depends on a recent feature."
  },
  {
    "id": "skills",
    "title": "skills",
    "when": "enriching a skill entry (trigger, examples, link)",
    "body": "Per-skill overlay. `name` must match a skill dir on disk.\n\n- `trigger` — a curated phrasing of *when this skill fires*. Falls back to the\n  SKILL.md description. Author it when a tighter, user-facing phrasing reads\n  better than the raw description.\n- `examples` — short example invocations / prompts that should trigger it.\n- `href` / `label` — a docs link for the skill.\n\n```yaml\nskills:\n  - name: marketplace-flow\n    trigger: When a user wants to turn a repo into a marketplace, fill\n      presentation data, generate the manifest, or wire CI.\n    examples:\n      - \"set up a marketplace\"\n      - \"generate the manifest\"\n```"
  },
  {
    "id": "commands",
    "title": "commands",
    "when": "enriching a slash-command entry",
    "body": "Per-command overlay. `name` must match a `commands/*.md` on disk.\n\n- `description` — curated one-liner; falls back to the command's native\n  description (first sentence). The argument table is derived natively — don't\n  restate it.\n- `examples` — example invocations.\n\n```yaml\ncommands:\n  - name: cc-check\n    description: Validate the marketplace without writing; explains any errors.\n    examples:\n      - \"/cc-check\"\n```"
  },
  {
    "id": "agents",
    "title": "agents",
    "when": "enriching an agent entry (returns, not, summary)",
    "body": "Per-agent overlay. `name` must match an `agents/*.md` on disk. Tools are derived\nnatively from frontmatter — don't restate them.\n\n- `description` — curated summary; falls back to native.\n- `returns` — what the agent hands back (its output contract). No native source.\n- `not` — explicit non-goals / what it won't do. Sets expectations; prevents\n  misuse.\n- `examples` — when to reach for it.\n\n```yaml\nagents:\n  - name: coverage-auditor\n    returns: A list of plugins missing presentation metadata, by dot-path.\n    not:\n      - It does not edit your entry.yaml — it only reports.\n```"
  },
  {
    "id": "mcp",
    "title": "mcp",
    "when": "enriching an MCP server entry (provides, install, auth, setup, env)",
    "body": "Per-MCP overlay. `name` must match a server in `.mcp.json`. Transport and env\nvar keys are derived natively. Author the human-facing context:\n\n- `provides` — the capabilities/tools it exposes, in plain language.\n- `install` — how to add it (one line or short steps).\n- `auth` — what credentials it needs and how to get them. Omit if none.\n- `setup` — any post-install configuration.\n- `env` — descriptions for env var keys (keys must already exist in `.mcp.json`;\n  an undescribed key is a warning, a phantom key is an error).\n- `repo` — source repository link.\n- `config` — settings the user can tune.\n\n```yaml\nmcp:\n  - name: cc-marketspec\n    provides:\n      - get_schema\n      - list_authoring_sections\n      - get_authoring_guide\n      - check_coverage\n      - scaffold_entry\n    install: Add the hosted endpoint to any Streamable-HTTP MCP client.\n    auth: None — the endpoint is open and read-only.\n```"
  },
  {
    "id": "hooks",
    "title": "hooks",
    "when": "explaining why a hook exists",
    "body": "Per-hook overlay. `event` / `matcher` must match a real entry in `hooks.json`\n(the generator checks). The only authored field:\n\n- `why` — why this hook exists / what it protects. No native source; the hook\n  config says what fires, not why it matters.\n\n```yaml\nhooks:\n  - event: PreToolUse\n    matcher: Write|Edit\n    why: Blocks writes that would desync the generated manifest from source.\n```"
  },
  {
    "id": "configuration",
    "title": "configuration",
    "when": "documenting plugin-local settings (.claude/<plugin>.local.md)",
    "body": "Document the plugin's local settings (the `.claude/<plugin>.local.md` file\nusers create). Each entry describes a setting: its key, what it does, and the\ndefault. No native source — this is pure documentation of your plugin's config\nsurface.\n\n```yaml\nconfiguration:\n  - key: strict_coverage\n    description: Fail the build on coverage warnings, not just errors.\n    default: \"false\"\n```"
  }
];
