import { z } from 'zod';
import { hookEvent } from './common.ts';

// The single consolidated data document a site renderer consumes (manifest.json).
// GENERATED by the framework (native plugin data joined with entry.yaml + derive +
// validate) — never hand-edited. This is the public, render-agnostic consumer API:
// site design is the consumer's. Identity is native; presentation is entry.yaml
// overlaid on native fallbacks; derived fields are computed by the generator.

const person = z
	.object({ name: z.string(), email: z.string().optional(), url: z.string().optional() })
	.strict();

const note = z
	.object({ text: z.string(), href: z.string().optional(), label: z.string().optional() })
	.strict();

const mSkill = z
	.object({
		name: z.string(),
		description: z.string().optional(),
		trigger: z.string().optional(),
		examples: z.array(z.string()).optional(),
		href: z.string().optional(),
		label: z.string().optional(),
		autoload: z.boolean().describe('Derived from native user-invocable: false.'),
		resources: z
			.object({
				scripts: z.number().int().min(0).optional(),
				references: z.number().int().min(0).optional(),
				assets: z.number().int().min(0).optional()
			})
			.strict()
			.optional()
	})
	.strict();

const mArgument = z
	.object({ name: z.string(), description: z.string().optional(), required: z.boolean().optional() })
	.strict();

const mCommand = z
	.object({
		name: z.string(),
		summary: z.string().describe('Derived: first sentence of native description.').optional(),
		description: z.string().optional(),
		arguments: z.array(mArgument).describe('Derived from native arguments / argument-hint.').optional(),
		examples: z.array(z.string()).optional()
	})
	.strict();

const mAgent = z
	.object({
		name: z.string(),
		summary: z.string().optional(),
		description: z.string().optional(),
		returns: z.string().optional(),
		not: z.string().optional(),
		tools: z.array(z.string()).describe('Derived from native frontmatter tools.').optional(),
		examples: z.array(z.string()).optional()
	})
	.strict();

const mMcpEnv = z
	.object({ key: z.string(), value: z.string().optional(), secret: z.boolean().optional() })
	.strict();

const mMcpSetup = z
	.object({
		text: z.string(),
		cmd: z.string().optional(),
		href: z.string().optional(),
		label: z.string().optional()
	})
	.strict();

const mMcp = z
	.object({
		name: z.string(),
		type: z.enum(['stdio', 'http', 'sse', 'ws']).describe('Derived from .mcp.json.'),
		install: z.boolean().optional(),
		auth: z.enum(['none', 'token', 'oauth']).optional(),
		repo: z.string().optional(),
		env: z.array(mMcpEnv).optional(),
		setup: z.array(mMcpSetup).optional(),
		description: z.string().optional(),
		provides: z.array(z.string()).describe('Authored, best-effort (not statically validated).').optional(),
		config: z.array(z.object({ key: z.string(), value: z.string() }).strict()).optional()
	})
	.strict();

const mHook = z
	.object({ event: hookEvent, matcher: z.string().optional(), why: z.string().optional() })
	.strict();

const mConfiguration = z
	.object({
		key: z.string(),
		type: z.enum(['string', 'boolean', 'number', 'array']),
		default: z.unknown().optional(),
		description: z.string(),
		required: z.boolean().optional()
	})
	.strict();

const mPlugin = z
	.object({
		id: z
			.string()
			.describe('Directory name = canonical id (== plugin.json name == marketplace.json entry name).'),
		name: z.string(),
		version: z.string(),
		description: z.string().describe('Native plugin description.').optional(),
		author: person.optional(),
		license: z.string().optional(),
		homepage: z.string().optional(),
		repository: z.string().optional(),
		keywords: z.array(z.string()).optional(),
		dependencies: z.array(z.string()).describe('Native plugin dependencies (ids).').optional(),
		category: z.string().describe('Native classification, derived from marketplace.json entry.').optional(),
		group: z.string().optional(),
		tagline: z.string().optional(),
		intro: z.string().optional(),
		ccVersion: z.string().describe('Resolved = max(self, all deps).').optional(),
		skills: z.array(mSkill).optional(),
		commands: z.array(mCommand).optional(),
		agents: z.array(mAgent).optional(),
		mcp: z.array(mMcp).optional(),
		hooks: z.array(mHook).optional(),
		configuration: z.array(mConfiguration).optional(),
		tips: z.array(note).optional(),
		traps: z.array(note).optional()
	})
	.strict();

const mGroup = z
	.object({ id: z.string(), label: z.string(), note: z.string().optional() })
	.strict();

export const Manifest = z
	.object({
		schemaVersion: z
			.string()
			.regex(/^\d+\.\d+$/)
			.describe('MAJOR.MINOR of the standard this manifest was generated against.'),
		marketplace: z
			.object({
				name: z.string(),
				description: z.string().optional(),
				lang: z.string().optional(),
				owner: person.optional()
			})
			.strict(),
		groups: z.array(mGroup).describe('Group taxonomy in display order.').optional(),
		plugins: z.array(mPlugin)
	})
	.strict();

export type Manifest = z.infer<typeof Manifest>;
