import { z } from 'zod';
import { hookEvent } from './common.ts';

// The single consolidated data document a site renderer consumes
// (.cc-marketspec/dist/manifest.json by default). GENERATED by the framework
// (native plugin data joined with .cc-marketspec/entries/plugin-<id>.yaml,
// derived, then validated) — never hand-edited. This is the public,
// render-agnostic consumer API: site design is the consumer's. Identity is
// native; namespaced presentation entries overlay native fallbacks; derived
// fields are computed by the generator.

const person = z
	.object({ name: z.string(), email: z.string().optional(), url: z.string().optional() })
	.strict();

const note = z
	.object({ text: z.string(), href: z.string().optional(), label: z.string().optional() })
	.strict();

const mSkill = z
	.object({
		name: z.string(),
		description: z.string().optional(),
		trigger: z.string().optional(),
		examples: z.array(z.string()).optional(),
		href: z.string().optional(),
		label: z.string().optional(),
		autoload: z.boolean().describe('Derived from native user-invocable: false.'),
		resources: z
			.object({
				scripts: z.number().int().min(0).optional(),
				references: z.number().int().min(0).optional(),
				assets: z.number().int().min(0).optional()
			})
			.strict()
			.optional()
	})
	.strict();

const mArgument = z
	.object({ name: z.string(), description: z.string().optional(), required: z.boolean().optional() })
	.strict();

const mCommand = z
	.object({
		name: z.string(),
		summary: z.string().describe('Derived: first sentence of native description.').optional(),
		description: z.string().optional(),
		arguments: z.array(mArgument).describe('Derived from native arguments / argument-hint.').optional(),
		examples: z.array(z.string()).optional()
	})
	.strict();

const mAgent = z
	.object({
		name: z.string(),
		summary: z.string().optional(),
		description: z.string().optional(),
		returns: z.string().optional(),
		not: z.string().optional(),
		tools: z.array(z.string()).describe('Derived from native frontmatter tools.').optional(),
		examples: z.array(z.string()).optional()
	})
	.strict();

const mMcpEnv = z
	.object({ key: z.string(), value: z.string().optional(), secret: z.boolean().optional() })
	.strict();

const mMcpSetup = z
	.object({
		text: z.string(),
		cmd: z.string().optional(),
		href: z.string().optional(),
		label: z.string().optional()
	})
	.strict();

const mMcp = z
	.object({
		name: z.string(),
		type: z.enum(['stdio', 'http', 'sse', 'ws']).describe('Derived from .mcp.json.'),
		install: z.boolean().optional(),
		auth: z.enum(['none', 'token', 'oauth']).optional(),
		repo: z.string().optional(),
		env: z.array(mMcpEnv).optional(),
		setup: z.array(mMcpSetup).optional(),
		description: z.string().optional(),
		provides: z.array(z.string()).describe('Authored, best-effort (not statically validated).').optional(),
		config: z.array(z.object({ key: z.string(), value: z.string() }).strict()).optional()
	})
	.strict();

const mHook = z
	.object({ event: hookEvent, matcher: z.string().optional(), why: z.string().optional() })
	.strict();

const mMod = z
	.object({
		module: z.string().describe('Derived: hooks module named under `modules` in a hooks file, relative to the plugin root.'),
		description: z.string().optional()
	})
	.strict();

const mConfiguration = z
	.object({
		key: z.string(),
		type: z.enum(['string', 'boolean', 'number', 'array', 'directory', 'file']),
		title: z.string().optional(),
		default: z.unknown().optional(),
		description: z.string().optional(),
		required: z.boolean().optional(),
		options: z.array(z.string()).optional(),
		multiple: z.boolean().optional(),
		sensitive: z.boolean().optional(),
		min: z.number().optional(),
		max: z.number().optional(),
		userConfig: z.boolean().describe('Derived: true when the key is a plugin.json userConfig field.').optional()
	})
	.strict();

const named = z.object({ name: z.string(), description: z.string().optional() }).strict();

const mPlugin = z
	.object({
		id: z
			.string()
			.describe('Directory name = canonical id (== plugin.json name == marketplace.json entry name).'),
		name: z.string(),
		displayName: z.string().describe('Native plugin.json displayName.').optional(),
		version: z.string(),
		description: z.string().describe('Native plugin description.').optional(),
		icon: z.string().describe('Native plugin.json icon path, relative to the plugin root.').optional(),
		defaultEnabled: z.boolean().describe('Native plugin.json defaultEnabled.').optional(),
		author: person.optional(),
		license: z.string().optional(),
		homepage: z.string().optional(),
		repository: z.string().optional(),
		keywords: z.array(z.string()).optional(),
		dependencies: z.array(z.string()).describe('Native plugin dependencies (`name` or `name@marketplace`).').optional(),
		category: z.string().describe('Native classification, derived from marketplace.json entry.').optional(),
		group: z.string().optional(),
		tagline: z.string().optional(),
		intro: z.string().optional(),
		ccVersion: z.string().describe('Resolved = max(self, all deps).').optional(),
		skills: z.array(mSkill).optional(),
		commands: z.array(mCommand).optional(),
		agents: z.array(mAgent).optional(),
		mcp: z.array(mMcp).optional(),
		hooks: z.array(mHook).optional(),
		mods: z.array(mMod).describe('Function-hook modules ("mods").').optional(),
		lsp: z
			.array(z.object({ name: z.string(), languages: z.array(z.string()) }).strict())
			.describe('Derived from .lsp.json / plugin.json lspServers.')
			.optional(),
		outputStyles: z.array(named).describe('Derived from output-styles/ / plugin.json outputStyles.').optional(),
		workflows: z.array(named).describe('Derived from workflows/ / plugin.json workflows.').optional(),
		themes: z
			.array(z.object({ name: z.string(), base: z.string().optional() }).strict())
			.describe('Derived from themes/ / plugin.json experimental.themes.')
			.optional(),
		monitors: z
			.array(z.object({ name: z.string(), description: z.string().optional(), when: z.string().optional() }).strict())
			.describe('Derived from monitors/monitors.json / plugin.json experimental.monitors.')
			.optional(),
		bin: z.array(z.string()).describe('Derived: executables in bin/.').optional(),
		channels: z
			.array(z.object({ server: z.string(), displayName: z.string().optional() }).strict())
			.describe('Derived from plugin.json channels.')
			.optional(),
		configuration: z
			.array(mConfiguration)
			.describe('plugin.json userConfig fields (derived) followed by authored-only settings.')
			.optional(),
		tips: z.array(note).optional(),
		traps: z.array(note).optional()
	})
	.strict();

const mGroup = z
	.object({ id: z.string(), label: z.string(), note: z.string().optional() })
	.strict();

export const Manifest = z
	.object({
		schemaVersion: z
			.string()
			.regex(/^\d+\.\d+$/)
			.describe('MAJOR.MINOR format compatibility version. This is not package SemVer; runtime compatibility is enforced by version.ts.'),
		marketplace: z
			.object({
				name: z.string(),
				description: z.string().optional(),
				lang: z.string().optional(),
				owner: person.optional()
			})
			.strict(),
		groups: z.array(mGroup).describe('Group taxonomy in display order.').optional(),
		plugins: z.array(mPlugin)
	})
	.strict();

export type Manifest = z.infer<typeof Manifest>;
