// AUTO-GENERATED by src/build.ts (npm run build:schemas). Do not edit by hand.
// Schemas are inlined from the Zod source of truth so getSchema and the MCP
// server run without a filesystem (e.g. Cloudflare Workers).
export const VERSION = "1.0.1";
export const SCHEMAS: Record<'entry' | 'catalog' | 'manifest', Record<string, unknown>> = {
  "entry": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "group": {
        "type": "string",
        "maxLength": 64,
        "description": "id of a .cc-marketspec/catalog.yaml group (authored). Native classification is surfaced separately as the manifest category.",
        "coverage": {
          "component": "plugin",
          "field": "group",
          "severity": "off"
        }
      },
      "tagline": {
        "type": "string",
        "minLength": 1,
        "maxLength": 120,
        "description": "One-line summary for cards/meta; falls back to native description.",
        "coverage": {
          "component": "plugin",
          "field": "tagline",
          "severity": "warn"
        }
      },
      "intro": {
        "type": "string",
        "minLength": 1,
        "maxLength": 600,
        "description": "Full lede; falls back to native description."
      },
      "ccVersion": {
        "type": "string",
        "pattern": "^\\d+\\.\\d+\\.\\d+$",
        "description": "Minimum Claude Code version. No native source."
      },
      "skills": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 64,
              "pattern": "^[a-z][a-z0-9-]*$"
            },
            "description": {
              "type": "string",
              "minLength": 1,
              "maxLength": 600,
              "description": "Curated human copy; falls back to native SKILL.md description."
            },
            "trigger": {
              "type": "string",
              "minLength": 1,
              "maxLength": 280,
              "description": "Human 'when to reach for it'.",
              "coverage": "warn"
            },
            "examples": {
              "maxItems": 5,
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1,
                "maxLength": 120
              },
              "coverage": "off"
            },
            "href": {
              "type": "string"
            },
            "label": {
              "type": "string",
              "maxLength": 120
            }
          },
          "required": [
            "name"
          ],
          "additionalProperties": false
        }
      },
      "commands": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 64,
              "pattern": "^[a-z][a-z0-9-]*$"
            },
            "description": {
              "type": "string",
              "minLength": 1,
              "maxLength": 600,
              "description": "Curated long copy; falls back to native.",
              "coverage": "off"
            },
            "examples": {
              "maxItems": 5,
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1,
                "maxLength": 120
              }
            }
          },
          "required": [
            "name"
          ],
          "additionalProperties": false
        }
      },
      "agents": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 64,
              "pattern": "^[a-z][a-z0-9-]*$"
            },
            "returns": {
              "type": "string",
              "minLength": 1,
              "maxLength": 280,
              "description": "What the agent reports back."
            },
            "not": {
              "type": "string",
              "minLength": 1,
              "maxLength": 280,
              "description": "Boundaries / what it will not do."
            },
            "description": {
              "type": "string",
              "minLength": 1,
              "maxLength": 600,
              "description": "Curated copy; falls back to native.",
              "coverage": {
                "component": "agent",
                "field": "summary",
                "severity": "warn"
              }
            },
            "examples": {
              "maxItems": 5,
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1,
                "maxLength": 120
              }
            }
          },
          "required": [
            "name"
          ],
          "additionalProperties": false
        }
      },
      "mcp": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1,
              "maxLength": 64,
              "description": "Server name; must match a server in .mcp.json."
            },
            "install": {
              "type": "boolean",
              "description": "Whether the user must install it themselves."
            },
            "auth": {
              "type": "string",
              "enum": [
                "none",
                "token",
                "oauth"
              ]
            },
            "repo": {
              "type": "string",
              "minLength": 1
            },
            "env": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "key": {
                    "type": "string",
                    "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
                  },
                  "value": {
                    "type": "string",
                    "minLength": 1,
                    "description": "Human description of the variable."
                  },
                  "secret": {
                    "type": "boolean"
                  }
                },
                "required": [
                  "key",
                  "value"
                ],
                "additionalProperties": false
              },
              "description": "Descriptions for env vars; keys must exist in .mcp.json (phantom = error).",
              "coverage": "warn"
            },
            "setup": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "text": {
                    "type": "string",
                    "minLength": 1
                  },
                  "cmd": {
                    "type": "string",
                    "minLength": 1
                  },
                  "href": {
                    "type": "string"
                  },
                  "label": {
                    "type": "string",
                    "maxLength": 120
                  }
                },
                "required": [
                  "text"
                ],
                "additionalProperties": false
              }
            },
            "description": {
              "type": "string",
              "minLength": 1,
              "maxLength": 600
            },
            "provides": {
              "minItems": 1,
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              },
              "description": "Tool names. AUTHORED, best-effort: not statically validatable (runtime-discovered).",
              "coverage": "off"
            },
            "config": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "key": {
                    "type": "string",
                    "minLength": 1
                  },
                  "value": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "key",
                  "value"
                ],
                "additionalProperties": false
              }
            }
          },
          "required": [
            "name"
          ],
          "additionalProperties": false
        }
      },
      "hooks": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "event": {
              "type": "string",
              "pattern": "^[A-Z][A-Za-z0-9]*$",
              "description": "Hook event name, e.g. ConfigChange, CwdChanged, DirectoryAdded, Elicitation."
            },
            "matcher": {
              "type": "string",
              "description": "Disambiguates when an event has multiple hooks."
            },
            "why": {
              "type": "string",
              "minLength": 1,
              "maxLength": 280,
              "description": "What this hook does / why it exists."
            }
          },
          "required": [
            "event"
          ],
          "additionalProperties": false
        }
      },
      "mods": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "module": {
              "type": "string",
              "minLength": 1,
              "description": "Hooks module path relative to the plugin root (e.g. hooks/register.tsx); must be named under `modules` in a hooks file."
            },
            "description": {
              "type": "string",
              "minLength": 1,
              "maxLength": 280,
              "description": "What the mod adds (a pane, a status line, a tool-call guard). A module is opaque to static analysis, so this is the only description.",
              "coverage": "warn"
            }
          },
          "required": [
            "module"
          ],
          "additionalProperties": false
        }
      },
      "configuration": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
            },
            "type": {
              "type": "string",
              "enum": [
                "string",
                "boolean",
                "number",
                "array",
                "directory",
                "file"
              ],
              "description": "Required unless the key is a plugin.json userConfig field (its type is derived)."
            },
            "default": {},
            "description": {
              "type": "string",
              "minLength": 1,
              "maxLength": 600
            },
            "required": {
              "type": "boolean"
            }
          },
          "required": [
            "key",
            "description"
          ],
          "additionalProperties": false
        }
      },
      "tips": {
        "type": "array",
        "items": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 280
            },
            {
              "type": "object",
              "properties": {
                "text": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 280
                },
                "href": {
                  "type": "string"
                },
                "label": {
                  "type": "string",
                  "maxLength": 120
                }
              },
              "required": [
                "text"
              ],
              "additionalProperties": false
            }
          ]
        },
        "description": "Positive power-moves."
      },
      "traps": {
        "type": "array",
        "items": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 280
            },
            {
              "type": "object",
              "properties": {
                "text": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 280
                },
                "href": {
                  "type": "string"
                },
                "label": {
                  "type": "string",
                  "maxLength": 120
                }
              },
              "required": [
                "text"
              ],
              "additionalProperties": false
            }
          ]
        },
        "description": "Negative gotchas / pitfalls."
      }
    },
    "additionalProperties": false,
    "$id": "https://raw.githubusercontent.com/XBlueSky/cc-marketspec/main/schemas/entry.schema.json",
    "title": "Marketplace plugin entry (presentation descriptor)"
  },
  "catalog": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "schemaVersion": {
        "type": "string",
        "pattern": "^\\d+\\.\\d+$",
        "description": "MAJOR.MINOR format compatibility version. This is not package SemVer; runtime compatibility is enforced by version.ts."
      },
      "lang": {
        "type": "string",
        "description": "BCP-47 primary language of all authored text (e.g. zh-TW). Defaults to en."
      },
      "groups": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "maxLength": 64,
              "pattern": "^[a-z][a-z0-9-]*$"
            },
            "label": {
              "type": "string",
              "minLength": 1,
              "maxLength": 120
            },
            "note": {
              "type": "string",
              "minLength": 1,
              "maxLength": 120,
              "description": "Short sub-label / description."
            }
          },
          "required": [
            "id",
            "label"
          ],
          "additionalProperties": false
        },
        "description": "Group taxonomy; array order is the canonical display order."
      },
      "coverage": {
        "type": "object",
        "propertyNames": {
          "type": "string"
        },
        "additionalProperties": {
          "type": "string",
          "enum": [
            "error",
            "warn",
            "off"
          ]
        },
        "description": "Per-rule severity overrides for the coverage gate."
      }
    },
    "required": [
      "schemaVersion"
    ],
    "additionalProperties": false,
    "$id": "https://raw.githubusercontent.com/XBlueSky/cc-marketspec/main/schemas/catalog.schema.json",
    "title": "Marketplace catalog (presentation)"
  },
  "manifest": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "schemaVersion": {
        "type": "string",
        "pattern": "^\\d+\\.\\d+$",
        "description": "MAJOR.MINOR format compatibility version. This is not package SemVer; runtime compatibility is enforced by version.ts."
      },
      "marketplace": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "lang": {
            "type": "string"
          },
          "owner": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name"
            ],
            "additionalProperties": false
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      },
      "groups": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "note": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "label"
          ],
          "additionalProperties": false
        },
        "description": "Group taxonomy in display order."
      },
      "plugins": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "Directory name = canonical id (== plugin.json name == marketplace.json entry name)."
            },
            "name": {
              "type": "string"
            },
            "displayName": {
              "type": "string",
              "description": "Native plugin.json displayName."
            },
            "version": {
              "type": "string"
            },
            "description": {
              "type": "string",
              "description": "Native plugin description."
            },
            "icon": {
              "type": "string",
              "description": "Native plugin.json icon path, relative to the plugin root."
            },
            "defaultEnabled": {
              "type": "boolean",
              "description": "Native plugin.json defaultEnabled."
            },
            "author": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "email": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ],
              "additionalProperties": false
            },
            "license": {
              "type": "string"
            },
            "homepage": {
              "type": "string"
            },
            "repository": {
              "type": "string"
            },
            "keywords": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "dependencies": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "Native plugin dependencies (`name` or `name@marketplace`)."
            },
            "category": {
              "type": "string",
              "description": "Native classification, derived from marketplace.json entry."
            },
            "group": {
              "type": "string"
            },
            "tagline": {
              "type": "string"
            },
            "intro": {
              "type": "string"
            },
            "ccVersion": {
              "type": "string",
              "description": "Resolved = max(self, all deps)."
            },
            "skills": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "trigger": {
                    "type": "string"
                  },
                  "examples": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "href": {
                    "type": "string"
                  },
                  "label": {
                    "type": "string"
                  },
                  "autoload": {
                    "type": "boolean",
                    "description": "Derived from native user-invocable: false."
                  },
                  "resources": {
                    "type": "object",
                    "properties": {
                      "scripts": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 9007199254740991
                      },
                      "references": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 9007199254740991
                      },
                      "assets": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 9007199254740991
                      }
                    },
                    "additionalProperties": false
                  }
                },
                "required": [
                  "name",
                  "autoload"
                ],
                "additionalProperties": false
              }
            },
            "commands": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "summary": {
                    "type": "string",
                    "description": "Derived: first sentence of native description."
                  },
                  "description": {
                    "type": "string"
                  },
                  "arguments": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "description": {
                          "type": "string"
                        },
                        "required": {
                          "type": "boolean"
                        }
                      },
                      "required": [
                        "name"
                      ],
                      "additionalProperties": false
                    },
                    "description": "Derived from native arguments / argument-hint."
                  },
                  "examples": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": [
                  "name"
                ],
                "additionalProperties": false
              }
            },
            "agents": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "summary": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "returns": {
                    "type": "string"
                  },
                  "not": {
                    "type": "string"
                  },
                  "tools": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "description": "Derived from native frontmatter tools."
                  },
                  "examples": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": [
                  "name"
                ],
                "additionalProperties": false
              }
            },
            "mcp": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "stdio",
                      "http",
                      "sse",
                      "ws"
                    ],
                    "description": "Derived from .mcp.json."
                  },
                  "install": {
                    "type": "boolean"
                  },
                  "auth": {
                    "type": "string",
                    "enum": [
                      "none",
                      "token",
                      "oauth"
                    ]
                  },
                  "repo": {
                    "type": "string"
                  },
                  "env": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "key": {
                          "type": "string"
                        },
                        "value": {
                          "type": "string"
                        },
                        "secret": {
                          "type": "boolean"
                        }
                      },
                      "required": [
                        "key"
                      ],
                      "additionalProperties": false
                    }
                  },
                  "setup": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "text": {
                          "type": "string"
                        },
                        "cmd": {
                          "type": "string"
                        },
                        "href": {
                          "type": "string"
                        },
                        "label": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "text"
                      ],
                      "additionalProperties": false
                    }
                  },
                  "description": {
                    "type": "string"
                  },
                  "provides": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "description": "Authored, best-effort (not statically validated)."
                  },
                  "config": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "key": {
                          "type": "string"
                        },
                        "value": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "key",
                        "value"
                      ],
                      "additionalProperties": false
                    }
                  }
                },
                "required": [
                  "name",
                  "type"
                ],
                "additionalProperties": false
              }
            },
            "hooks": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "event": {
                    "type": "string",
                    "pattern": "^[A-Z][A-Za-z0-9]*$",
                    "description": "Hook event name, e.g. ConfigChange, CwdChanged, DirectoryAdded, Elicitation."
                  },
                  "matcher": {
                    "type": "string"
                  },
                  "why": {
                    "type": "string"
                  }
                },
                "required": [
                  "event"
                ],
                "additionalProperties": false
              }
            },
            "mods": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "module": {
                    "type": "string",
                    "description": "Derived: hooks module named under `modules` in a hooks file, relative to the plugin root."
                  },
                  "description": {
                    "type": "string"
                  }
                },
                "required": [
                  "module"
                ],
                "additionalProperties": false
              },
              "description": "Function-hook modules (\"mods\")."
            },
            "lsp": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "languages": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": [
                  "name",
                  "languages"
                ],
                "additionalProperties": false
              },
              "description": "Derived from .lsp.json / plugin.json lspServers."
            },
            "outputStyles": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "additionalProperties": false
              },
              "description": "Derived from output-styles/ / plugin.json outputStyles."
            },
            "workflows": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "additionalProperties": false
              },
              "description": "Derived from workflows/ / plugin.json workflows."
            },
            "themes": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "base": {
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "additionalProperties": false
              },
              "description": "Derived from themes/ / plugin.json experimental.themes."
            },
            "monitors": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "when": {
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "additionalProperties": false
              },
              "description": "Derived from monitors/monitors.json / plugin.json experimental.monitors."
            },
            "bin": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "Derived: executables in bin/."
            },
            "channels": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "server": {
                    "type": "string"
                  },
                  "displayName": {
                    "type": "string"
                  }
                },
                "required": [
                  "server"
                ],
                "additionalProperties": false
              },
              "description": "Derived from plugin.json channels."
            },
            "configuration": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "key": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "string",
                      "boolean",
                      "number",
                      "array",
                      "directory",
                      "file"
                    ]
                  },
                  "title": {
                    "type": "string"
                  },
                  "default": {},
                  "description": {
                    "type": "string"
                  },
                  "required": {
                    "type": "boolean"
                  },
                  "options": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "multiple": {
                    "type": "boolean"
                  },
                  "sensitive": {
                    "type": "boolean"
                  },
                  "min": {
                    "type": "number"
                  },
                  "max": {
                    "type": "number"
                  },
                  "userConfig": {
                    "type": "boolean",
                    "description": "Derived: true when the key is a plugin.json userConfig field."
                  }
                },
                "required": [
                  "key",
                  "type"
                ],
                "additionalProperties": false
              },
              "description": "plugin.json userConfig fields (derived) followed by authored-only settings."
            },
            "tips": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "text": {
                    "type": "string"
                  },
                  "href": {
                    "type": "string"
                  },
                  "label": {
                    "type": "string"
                  }
                },
                "required": [
                  "text"
                ],
                "additionalProperties": false
              }
            },
            "traps": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "text": {
                    "type": "string"
                  },
                  "href": {
                    "type": "string"
                  },
                  "label": {
                    "type": "string"
                  }
                },
                "required": [
                  "text"
                ],
                "additionalProperties": false
              }
            }
          },
          "required": [
            "id",
            "name",
            "version"
          ],
          "additionalProperties": false
        }
      }
    },
    "required": [
      "schemaVersion",
      "marketplace",
      "plugins"
    ],
    "additionalProperties": false,
    "$id": "https://raw.githubusercontent.com/XBlueSky/cc-marketspec/main/schemas/manifest.schema.json",
    "title": "Marketplace manifest (generated consumer API)"
  }
};
